name: metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: KioFatto.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: KioFatto
          config_timezone: Europe/Rome
          base: header, activity, community, repositories
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_languages: yes
          plugin_languages_details: percentage